// Student Status Constants
export const STUDENT_STATUS = {
  NEW_USER: 0,
  PROFILE_UPDATE_PENDING: 1,
  PERSONAL_DOCUMENTS_PENDING: 2,
  PERSONAL_DOCUMENTS_SUBMITTED: 3,
  INTERVIEW_SCHEDULED: 4,
  ACADEMIC_DOCUMENTS_PENDING: 5,
  ACADEMIC_DOCUMENTS_SUBMITTED: 6,
  ELIGIBLE_FOR_SCHOLARSHIP: 7,
  PAYMENT_PENDING: 8,
  PAID: 9,
  PAYMENT_VERIFIED: 10,
  RECEIPT_DOCUMENTS_SUBMITTED: 11,
  ALUMNI: 12,
  BLOCKED: 13,
} as const;

// Status mapping for display names
export const STUDENT_STATUS_DISPLAY = {
  [STUDENT_STATUS.NEW_USER]: 'New User',
  [STUDENT_STATUS.PROFILE_UPDATE_PENDING]: 'Profile Update Pending',
  [STUDENT_STATUS.PERSONAL_DOCUMENTS_PENDING]: 'Personal Documents Pending',
  [STUDENT_STATUS.PERSONAL_DOCUMENTS_SUBMITTED]: 'Personal Documents Submitted',
  [STUDENT_STATUS.INTERVIEW_SCHEDULED]: 'Interview Scheduled',
  [STUDENT_STATUS.ACADEMIC_DOCUMENTS_PENDING]: 'Academic Documents Pending',
  [STUDENT_STATUS.ACADEMIC_DOCUMENTS_SUBMITTED]: 'Academic Documents Submitted',
  [STUDENT_STATUS.ELIGIBLE_FOR_SCHOLARSHIP]: 'Eligible for Scholarship',
  [STUDENT_STATUS.PAYMENT_PENDING]: 'Payment Pending',
  [STUDENT_STATUS.PAID]: 'Paid',
  [STUDENT_STATUS.PAYMENT_VERIFIED]: 'Payment Verified',
  [STUDENT_STATUS.RECEIPT_DOCUMENTS_SUBMITTED]: 'Receipt Documents Submitted',
  [STUDENT_STATUS.ALUMNI]: 'Alumni',
  [STUDENT_STATUS.BLOCKED]: 'Blocked',
} as const;

export type StudentStatusType = typeof STUDENT_STATUS[keyof typeof STUDENT_STATUS]; 