// Student Status Constants
export const STUDENT_STATUS = {
  NEW_USER: 0,
  PERSONAL_DETAILS_PENDING: 1,
  PERSONAL_DETAILS_SUBMITTED: 2,
  INTERVIEW_SCHEDULED: 3,
  ACADEMIC_DOCUMENTS_PENDING: 4,
  ACADEMIC_DOCUMENTS_SUBMITTED: 5,
  ELIGIBLE_FOR_SCHOLARSHIP: 6,
  PAYMENT_PENDING: 7,
  PAID: 8,
  PAYMENT_VERIFIED: 9,
  RECEIPT_DOCUMENTS_SUBMITTED: 10,
  ALUMNI: 11,
  BLOCKED: 12,
} as const;

// Status mapping for display names
export const STUDENT_STATUS_DISPLAY = {
  [STUDENT_STATUS.NEW_USER]: 'New User',
  [STUDENT_STATUS.PERSONAL_DETAILS_PENDING]: 'Personal Details Pending',
  [STUDENT_STATUS.PERSONAL_DETAILS_SUBMITTED]: 'Personal Details Submitted',
  [STUDENT_STATUS.INTERVIEW_SCHEDULED]: 'Interview Scheduled',
  [STUDENT_STATUS.ACADEMIC_DOCUMENTS_PENDING]: 'Academic Documents Pending',
  [STUDENT_STATUS.ACADEMIC_DOCUMENTS_SUBMITTED]: 'Academic Documents Submitted',
  [STUDENT_STATUS.ELIGIBLE_FOR_SCHOLARSHIP]: 'Eligible for Scholarship',
  [STUDENT_STATUS.PAYMENT_PENDING]: 'Payment Pending',
  [STUDENT_STATUS.PAID]: 'Paid',
  [STUDENT_STATUS.PAYMENT_VERIFIED]: 'Payment Verified',
  [STUDENT_STATUS.RECEIPT_DOCUMENTS_SUBMITTED]: 'Receipt Documents Submitted',
  [STUDENT_STATUS.ALUMNI]: 'Alumni',
  [STUDENT_STATUS.BLOCKED]: 'Blocked',
} as const;

export type StudentStatusType = typeof STUDENT_STATUS[keyof typeof STUDENT_STATUS]; 