// Student Status Constants
export const STUDENT_STATUS = {
  NEW_USER: 0,
  MOBILE_VERIFIED: 1,
  PROFILE_UPDATED: 2,
  PERSONAL_DOCUMENTS_PENDING: 3,
  PERSONAL_DOCUMENTS_SUBMITTED: 4,
  INTERVIEW_SCHEDULED: 5,
  ACADEMIC_DOCUMENTS_PENDING: 6,
  ACADEMIC_DOCUMENTS_SUBMITTED: 7,
  ELIGIBLE_FOR_SCHOLARSHIP: 8,
  PAYMENT_PENDING: 9,
  PAID: 10,
  RECEIPT_DOCUMENTS_SUBMITTED: 11,
  ALUMNI: 12,
  BLOCKED: 13,
} as const;

// Status mapping for display names
export const STUDENT_STATUS_DISPLAY = {
  [STUDENT_STATUS.NEW_USER]: 'New User',
  [STUDENT_STATUS.MOBILE_VERIFIED]: 'Mobile Verified',
  [STUDENT_STATUS.PROFILE_UPDATED]: 'Profile Updated',
  [STUDENT_STATUS.PERSONAL_DOCUMENTS_PENDING]: 'Personal Documents Pending',
  [STUDENT_STATUS.PERSONAL_DOCUMENTS_SUBMITTED]: 'Personal Documents Submitted',
  [STUDENT_STATUS.INTERVIEW_SCHEDULED]: 'Interview Scheduled',
  [STUDENT_STATUS.ACADEMIC_DOCUMENTS_PENDING]: 'Academic Documents Pending',
  [STUDENT_STATUS.ACADEMIC_DOCUMENTS_SUBMITTED]: 'Academic Documents Submitted',
  [STUDENT_STATUS.ELIGIBLE_FOR_SCHOLARSHIP]: 'Eligible for Scholarship',
  [STUDENT_STATUS.PAYMENT_PENDING]: 'Payment Pending',
  [STUDENT_STATUS.PAID]: 'Paid',
  [STUDENT_STATUS.RECEIPT_DOCUMENTS_SUBMITTED]: 'Receipt Documents Submitted',
  [STUDENT_STATUS.ALUMNI]: 'Alumni',
  [STUDENT_STATUS.BLOCKED]: 'Blocked',
} as const;

export type StudentStatusType = typeof STUDENT_STATUS[keyof typeof STUDENT_STATUS]; 